import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { validateTemplateManifest } from "./validate-manifest.mjs";

export function renderNodeService({ name = "generated-service" } = {}) {
  if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name)) throw new Error("service name is invalid");
  return {
    "package.json": JSON.stringify({ name, version: "0.1.0", private: true, type: "module", scripts: { start: "node src/server.mjs" } }, null, 2) + "\n",
    "src/server.mjs": "import { createServer } from \"node:http\";\ncreateServer((_, res) => res.end(\"ok\\n\")).listen(3000);\n",
    "README.md": `# ${name}\n\nGenerated by ZAI Factory. No secrets or deployment identifiers are included.\n`,
  };
}

export async function generateProject({ manifest, outputDir, values = {} }) {
  validateTemplateManifest(manifest);
  if (!outputDir || outputDir.includes("..")) throw new Error("outputDir is invalid");
  const rendered = renderNodeService(values);
  for (const file of manifest.files) {
    const content = rendered[file.path];
    if (typeof content !== "string") throw new Error(`missing rendered file: ${file.path}`);
    const target = join(outputDir, file.path);
    await mkdir(join(target, ".."), { recursive: true });
    await writeFile(target, content, "utf8");
  }
  return { outputDir, files: manifest.files.map((file) => ({ path: file.path, owner: file.owner })) };
}
