<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <WindowsAppSdkVersion>2.3.1</WindowsAppSdkVersion>
    <WindowsSdkBuildToolsVersion>10.0.26100.8249</WindowsSdkBuildToolsVersion>
    <WindowsSdkMsixVersion>1.7.260610101</WindowsSdkMsixVersion>
    <SystemSecurityPermissionsVersion>8.0.0</SystemSecurityPermissionsVersion>
    <SystemWindowsExtensionsVersion>8.0.0</SystemWindowsExtensionsVersion>
    <TestSdkVersion>18.8.1</TestSdkVersion>
    <XunitVersion>2.9.3</XunitVersion>
    <XunitRunnerVersion>4.0.0</XunitRunnerVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="$(WindowsAppSdkVersion)" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="$(WindowsSdkBuildToolsVersion)" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="$(WindowsSdkMsixVersion)" />
    <PackageVersion Include="System.Security.Permissions" Version="$(SystemSecurityPermissionsVersion)" />
    <PackageVersion Include="System.Windows.Extensions" Version="$(SystemWindowsExtensionsVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageVersion Include="xunit" Version="$(XunitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
  </ItemGroup>
</Project>
